[workspace]
members = ["2019/day3/part1", "2023", "2024", "2025"]
resolver = "3"

[workspace.dependencies]
itertools = "0.14.0"
nom = "8.0.0"
assert_matches = "1.5.0"
rayon = "1.11.0"
anyhow = "1.0.100"
